version: '3'

services:
  nginx:
    build: docker/nginx
    container_name: nginx
    networks:
      - app_network
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/default.nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: docker/php
    container_name: php
    networks:
      - app_network
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: learning_php
      MYSQL_USER: learning_php
      MYSQL_PASSWORD: learning_php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./src:/var/www
    working_dir: /var/www/learning
    depends_on:
      - db

  cron:
    container_name: cron
    build: docker/cron
    networks:
      - app_network
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: learning_php
      MYSQL_USER: learning_php
      MYSQL_PASSWORD: learning_php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini # php の php.iniを参照
      - ./docker/cron/cron_root.txt:/var/spool/cron/crontabs/root
      - ./docker/cron/tmp:/tmp/cron
      - ./src:/var/www
    working_dir: /var/www/learning
    depends_on:
      - db

  db:
    build: docker/db
    container_name: db
    networks:
      - app_network
    environment:
      MYSQL_DATABASE: learning_php
      MYSQL_USER: learning_php
      MYSQL_PASSWORD: learning_php
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/log:/var/log/mysql
      - mysql_volume:/var/lib/mysql
    command: mysqld --slow_query_log=0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - app_network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - "8000:80"
    volumes:
      - /sessions
    depends_on:
      - db

networks:
  app_network:

volumes:
  mysql_volume:
